#version 430 core

// input
layout (rgba32f, binding = 0) uniform image2D EROSIONMAP_READ;
// output
layout (rgba32f, binding = 1) uniform image2D EROSIONMAP_WRITE; 

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

void main(void)
{
	ivec2 uv = ivec2(gl_GlobalInvocationID.xy);

	float rain = imageLoad(EROSIONMAP_READ, uv).g;
	//rain += 1.0 * 4.5;
	rain += 0.02;

	vec4 color = imageLoad(EROSIONMAP_READ, uv);
	color.g = rain;

	imageStore(EROSIONMAP_WRITE, uv, color);
}
