#version 430 core

layout (binding = 0) uniform sampler2D INPUT;
layout (rgba32f, binding = 1) uniform image2D OUTPUT;

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

uniform float TEXTURE_WIDTH;
uniform float TEXTURE_HEIGHT;

void main(void)
{
	ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
	vec2 scaled = vec2(uv.x/TEXTURE_WIDTH, uv.y/TEXTURE_HEIGHT);

	vec4 color = texture(INPUT, scaled);

	imageStore(OUTPUT, uv, color);
}
