#version 430 core

layout (binding = 0) uniform sampler2D INPUT;
layout (rgba32f, binding = 1) uniform image2D OUTPUT;

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main(void)
{
	ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
	vec2 scaled = vec2(uv.x/1920.0, uv.y/1080.0); // TODO better way to copy FBO

	vec4 color = texture(INPUT, scaled);

	imageStore(OUTPUT, uv, color);
}
